import parsealbumfolder
import sys
import os

def generateAlbumPage(path):
    albumData = parsealbumfolder.parseAlbumFolder(path)
    if albumData == None:
        print "Problem parsing folder " + path
        print "Exitting"
        sys.exit(0)

    imageListHtml = ""
    for imageData in albumData["images"]:
        imageTitleHtml = ""
        if "title" in imageData:
            imageTitleHtml = "<h2>" + imageData["title"] + "</h2>"
        imageDescriptionHtml = ""
        if "description" in imageData:
            imageDescriptionHtml = "<p>" + imageData["description"] + "</p>"
        imageListHtml += """
      <div class="image">
        <img src=\"""" + imageData["path"] + """" />
        """ + imageTitleHtml + """
        """ + imageDescriptionHtml + """
      </div>
"""

    htmlContent = """<!-- Generated by """ + os.path.basename(__file__) + """ -->
<html>
  <head>
    <title>""" + albumData["title"] + """</title>
    <link rel="stylesheet" type="text/css" href="../../css/buildalbum.css">
  </head>

  <body>
    <div class="albumintro">
      <h1>""" + albumData["title"] + """</h1>
      <p>""" + albumData["description"] + """</p>
      <img src=\"""" + albumData["coverimagepath"] + """" />
    </div>

    <div class="album">
""" + imageListHtml + """
    </div>
  </body>
</html>
"""

    with open(path + "/index.html", "w") as htmlFile:
        print "Writing " + path + "/index.html"
        htmlFile.write(htmlContent.encode("utf-8"))

def main():
    scriptDirectoryPath = os.path.dirname(os.path.realpath(__file__)) + "/"
    websiteRoot = scriptDirectoryPath + "../"
    buildsDirectory = websiteRoot + "builds/"

    for subpath in os.listdir(buildsDirectory):
        path = buildsDirectory + subpath
        if os.path.isdir(path):
            albumJsonPath = path + "/album.json"
            if os.path.isfile(albumJsonPath):
                generateAlbumPage(path)


main()
